// <auto-generated />
using System;
using HotelBookingSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelBookingSystem.Infrastructure.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20231214005841_Initial")]
partial class Initial
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("HotelBookingSystem.Domain.Models.Booking", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateOnly>("CheckInDate")
                    .HasColumnType("date");

                b.Property<DateOnly>("CheckOutDate")
                    .HasColumnType("date");

                b.Property<DateTime>("CreationDate")
                    .HasColumnType("datetime2");

                b.Property<Guid>("GuestId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("LastModified")
                    .HasColumnType("datetime2");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,2)");

                b.Property<Guid>("RoomId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("GuestId");

                b.HasIndex("RoomId");

                b.ToTable("Bookings");
            });

        modelBuilder.Entity("HotelBookingSystem.Domain.Models.City", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Country")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreationDate")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("LastModified")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PostOffice")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Cities");
            });

        modelBuilder.Entity("HotelBookingSystem.Domain.Models.Guest", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreationDate")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("LastModified")
                    .HasColumnType("datetime2");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Guests");
            });

        modelBuilder.Entity("HotelBookingSystem.Domain.Models.Hotel", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<TimeOnly>("CheckInTime")
                    .HasColumnType("time");

                b.Property<TimeOnly>("CheckOutTime")
                    .HasColumnType("time");

                b.Property<Guid>("CityId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreationDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("LastModified")
                    .HasColumnType("datetime2");

                b.Property<string>("Location")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Owner")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<short>("StarRate")
                    .HasColumnType("smallint");

                b.HasKey("Id");

                b.HasIndex("CityId");

                b.ToTable("Hotels");
            });

        modelBuilder.Entity("HotelBookingSystem.Domain.Models.HotelImage", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreationDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Format")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("HotelId")
                    .HasColumnType("uniqueidentifier");

                b.Property<byte[]>("ImageData")
                    .IsRequired()
                    .HasColumnType("varbinary(max)");

                b.Property<DateTime>("LastModified")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("HotelId");

                b.ToTable("HotelImages");
            });

        modelBuilder.Entity("HotelBookingSystem.Domain.Models.Review", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreationDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("GuestId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("HotelId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("LastModified")
                    .HasColumnType("datetime2");

                b.Property<short>("Rating")
                    .HasColumnType("smallint");

                b.Property<string>("Title")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("GuestId");

                b.HasIndex("HotelId");

                b.ToTable("Reviews");
            });

        modelBuilder.Entity("HotelBookingSystem.Domain.Models.Room", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("AdultsCapacity")
                    .HasColumnType("int");

                b.Property<int>("ChildrenCapacity")
                    .HasColumnType("int");

                b.Property<DateTime>("CreationDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("HotelId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("LastModified")
                    .HasColumnType("datetime2");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("RoomNumber")
                    .HasColumnType("int");

                b.Property<int>("RoomType")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("HotelId");

                b.ToTable("Rooms");
            });

        modelBuilder.Entity("HotelBookingSystem.Domain.Models.RoomImage", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreationDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Format")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<byte[]>("ImageData")
                    .IsRequired()
                    .HasColumnType("varbinary(max)");

                b.Property<DateTime>("LastModified")
                    .HasColumnType("datetime2");

                b.Property<Guid>("RoomId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("RoomId");

                b.ToTable("RoomImages");
            });

        modelBuilder.Entity("HotelBookingSystem.Domain.Models.Booking", b =>
            {
                b.HasOne("HotelBookingSystem.Domain.Models.Guest", "Guest")
                    .WithMany("Reservations")
                    .HasForeignKey("GuestId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("HotelBookingSystem.Domain.Models.Room", "Room")
                    .WithMany()
                    .HasForeignKey("RoomId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Guest");

                b.Navigation("Room");
            });

        modelBuilder.Entity("HotelBookingSystem.Domain.Models.Hotel", b =>
            {
                b.HasOne("HotelBookingSystem.Domain.Models.City", "City")
                    .WithMany("Hotels")
                    .HasForeignKey("CityId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("City");
            });

        modelBuilder.Entity("HotelBookingSystem.Domain.Models.HotelImage", b =>
            {
                b.HasOne("HotelBookingSystem.Domain.Models.Hotel", null)
                    .WithMany("Images")
                    .HasForeignKey("HotelId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("HotelBookingSystem.Domain.Models.Review", b =>
            {
                b.HasOne("HotelBookingSystem.Domain.Models.Guest", "Guest")
                    .WithMany()
                    .HasForeignKey("GuestId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("HotelBookingSystem.Domain.Models.Hotel", "Hotel")
                    .WithMany("Reviews")
                    .HasForeignKey("HotelId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Guest");

                b.Navigation("Hotel");
            });

        modelBuilder.Entity("HotelBookingSystem.Domain.Models.Room", b =>
            {
                b.HasOne("HotelBookingSystem.Domain.Models.Hotel", "Hotel")
                    .WithMany("Rooms")
                    .HasForeignKey("HotelId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Hotel");
            });

        modelBuilder.Entity("HotelBookingSystem.Domain.Models.RoomImage", b =>
            {
                b.HasOne("HotelBookingSystem.Domain.Models.Room", null)
                    .WithMany("Images")
                    .HasForeignKey("RoomId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("HotelBookingSystem.Domain.Models.City", b =>
            {
                b.Navigation("Hotels");
            });

        modelBuilder.Entity("HotelBookingSystem.Domain.Models.Guest", b =>
            {
                b.Navigation("Reservations");
            });

        modelBuilder.Entity("HotelBookingSystem.Domain.Models.Hotel", b =>
            {
                b.Navigation("Images");

                b.Navigation("Reviews");

                b.Navigation("Rooms");
            });

        modelBuilder.Entity("HotelBookingSystem.Domain.Models.Room", b =>
            {
                b.Navigation("Images");
            });
#pragma warning restore 612, 618
    }
}
