global using Xunit;
global using AutoFixture;
global using AutoFixture.AutoMoq;
global using AutoMapper;
global using HotelBookingSystem.Application.Exceptions;
global using HotelBookingSystem.Application.Services;
global using HotelBookingSystem.Domain.Abstractions.Repositories;
global using HotelBookingSystem.Domain.Models;
global using Moq;